export const TOPICS = [
  'AI Bias & Fairness',
  'AI Safety & Robustness',
  'Academic Integrity',
  'Activism & Social Movements',
  'Aesthetic & Artistic Quality',
  'Agricultural Extension & Farming Practices',
  'Anthropomorphism',
  'Architecture',
  'Armed Conflict & International Humanitarian Law',
  'Art History',
  'Astronomy & Cosmology',
  'Audio-Visual Misinformation',
  'Autonomous Agent Security',
  'Biology',
  'Business & Management',
  'Causal Reasoning',
  'Central Africa',
  'Central America',
  'Central Asia',
  'Chemistry',
  'Child Safety & Protection',
  'Civil Liberties & State Powers',
  'Climate Change',
  'Climate Change Adaptation',
  'Cognitive Impact & Dependency',
  'Coding',
  'Constitutional Law',
  'Consumer Protection',
  'Creative Writing',
  'Cultural Competency',
  'Cultural Heritage & Language Preservation',
  'Customary & Traditional Law',
  'Data Privacy & Bodily Autonomy',
  'Deepfake & Synthetic Detection',
  'Dehumanization',
  'Democratic Processes',
  'Digital & Financial Inclusion',
  'Disability Rights',
  'Earth & Environmental Science',
  'East Africa',
  'East Asia',
  'Eastern Europe',
  'Economic Disruption & Reskilling Advice',
  'Economic Justice & Inequality',
  'Economics & Finance',
  'Education Systems & Pedagogy',
  'Electoral Rights & Voter Eligibility',
  'Engineering',
  'Environmental Justice & Activism',
  'Environmental Rights & Law',
  'Equality & Anti-Discrimination',
  'Factual Accuracy & Hallucination',
  'Financial Regulation',
  'Fraud Detection',
  'Freedom of Information',
  'Gender & Sexuality',
  'General Knowledge',
  'Geography',
  'Geographic & Local Knowledge',
  'Global South Agriculture & Ecology',
  'Healthcare & Clinical Scenarios',
  'Healthcare',
  'History',
  'Historical Accuracy & Misinformation',
  'Housing Rights & Eviction',
  'Human Rights',
  'Humanities',
  'Immigration & Refugee Rights',
  'Indigenous Peoples\' Rights',
  'Informal Economies & Livelihoods',
  'Information Ecology & Synthetic Content Proliferation',
  'Instruction Following & Prompt Adherence',
  'Interpersonal & Social Skill Modeling',
  'International Law & Regional Charters',
  'Jailbreak & Evasion Resistance',
  'Labor & Workers\' Rights',
  'Language & Dialect Nuance',
  'Law Enforcement & Criminal Justice',
  'Legal Reasoning',
  'Literary Analysis & Criticism',
  'Logical & Rhetorical Fallacies',
  'Long-form Question Answering',
  'Low-Resource Language Proficiency',
  'Maternal & Child Health',
  'Mathematics & Statistics',
  'Mental Health & Crisis Support',
  'Middle East & North Africa (MENA)',
  'Misinformation & Disinformation',
  'Mourning & Grief',
  'Multilingual Reasoning',
  'Music Theory & History',
  'Non-Western Philosophical Frameworks',
  'Nordic Countries',
  'North America',
  'Nutrition, Fitness, & Wellness',
  'Oceania',
  'Oral Traditions & Unwritten Knowledge',
  'Personal Finance & Financial Literacy',
  'Philosophy & Ethics',
  'Physics',
  'Platform & Gig Worker Rights',
  'Political Science',
  'Professional Development & Workplace Skills',
  'Psychology',
  'Public Health Communication',
  'Public Sector & Governance',
  'Racial Justice',
  'Real Estate & Property Law',
  'Reasoning',
  'Religious & Faith-based Reasoning',
  'Role-playing',
  'Rule of Law',
  'Safety',
  'Science Communication',
  'Sociology & Anthropology',
  'South America',
  'South Asia',
  'Southeast Asia (SEA)',
  'Southern Africa',
  'Southern Europe',
  'Sycophancy & Evasion',
  'Sycophancy',
  'System Prompt Adherence',
  'Summarization',
  'Task Planning & Decomposition',
  'Tax Law & Fairness',
  'The Balkans',
  'The Caribbean',
  'Tool Use & API Adherence',
  'Traditional & Indigenous Medicine',
  'Translation',
  'US Civil Rights Movement',
  'Urban Planning & Informal Settlements',
  'Visual Stereotyping & Bias',
  'Vocational Training & Skilled Trades',
  'West Africa',
  'Western Europe',

  // OECD capability indicators:
  'Language',
  'Social interaction',
  'Problem solving',
  'Creativity',
  'Metacognition and critical thinking',
  'Knowledge, learning and memory'
] as const;

export type Topic = typeof TOPICS[number]; 