export const TOPICS = [
  'AI Bias & Fairness',
  'AI Safety & Robustness',
  'Academic Integrity',
  'Anthropomorphism',
  'Armed Conflict & International Humanitarian Law',
  'Causal Reasoning',
  'Child Safety & Protection',
  'Civil Liberties & State Powers',
  'Climate Change',
  'Constitutional Law',
  'Consumer Protection',
  'Cultural Competency',
  'Data Privacy & Bodily Autonomy',
  'Dehumanization',
  'Democratic Processes',
  'Disability Rights',
  'Economic Justice & Inequality',
  'Electoral Rights & Voter Eligibility',
  'Environmental Rights & Law',
  'Equality & Anti-Discrimination',
  'Factual Accuracy & Hallucination',
  'Financial Regulation',
  'Fraud Detection',
  'Freedom of Information & RTI',
  'Gender & Sexuality Probes',
  'Geographic & Local Knowledge',
  'Healthcare & Clinical Scenarios',
  'Historical Accuracy & Misinformation',
  'Housing Rights & Eviction',
  'Human Rights',
  'Immigration & Refugee Rights',
  'Indigenous Peoples\' Rights',
  'Instruction Following & Prompt Adherence',
  'International Law & Regional Charters',
  'Labor & Workers\' Rights',
  'Legal Reasoning',
  'Logical & Rhetorical Fallacies',
  'Long-form Question Answering',
  'Maternal & Child Health',
  'Mental Health & Crisis Support',
  'Misinformation & Disinformation',
  'Multilingual Reasoning',
  'Public Health Communication',
  'Public Sector & Governance',
  'Racial Justice',
  'Rule of Law',
  'Science Communication',
  'Sycophancy & Evasion',
  'Tax Law & Fairness',
  'US Civil Rights Movement',
  'Coding',
  'Creative Writing',
  'STEM',
  'Humanities',
  'Safety',
  'Translation',
  'Summarization',
  'Reasoning',
  'General Knowledge',
  'Role-playing'
] as const;

export type Topic = typeof TOPICS[number]; 