import {
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  Check,
  Circle,
  AlertTriangle,
  TriangleAlert,
  Info,
  BookOpen,
  BookOpenCheck,
  Edit3,
  Scale,
  BarChartHorizontalBig,
  BarChart3,
  Award,
  FlaskConical,
  BrainCircuit,
  FolderOpen,
  Tag,
  ArrowRight,
  ArrowLeft,
  ArrowDownRight,
  ArrowUpRight,
  Trash2,
  Trash,
  PackageSearch,
  Copy,
  Plus,
  CheckCircle,
  CheckCircle2,
  XCircle,
  Loader2,
  Sparkles,
  Save,
  GitPullRequest,
  Github,
  MoreVertical,
  MoreHorizontal,
  History,
  ExternalLink,
  HelpCircle,
  Pencil,
  FileCode2,
  File,
  FileText,
  GitPullRequestClosed,
  RefreshCw,
  GitMerge,
  Trophy,
  AlertCircle,
  GitCommit,
  Quote,
  MessageSquare,
  MessageCircle,
  Layers,
  Hash,
  LayoutGrid,
  HardDriveDownload,
  Wand2,
  LogIn,
  LogOut,
  PlayCircle,
  Search,
  SearchX,
  Bot,
  User,
  Users,
  Thermometer,
  Unlink,
  SlidersHorizontal,
  BarChartBig,
  ChevronsUpDown,
  Terminal,
  ThumbsDown,
  Server,
  Download,
  TrendingUp,
  TrendingDown,
  Star,
  Eye,
  Wand,
  Activity,
  Target,
  Medal,
  GitCompareArrows,
  Puzzle,
  Shield,
  Compass,
  Globe,
  AlignLeft,
  GitBranch,
  Minimize2,
  Maximize2,
  Cpu,
  Undo,
  Keyboard,
  type LucideProps
} from 'lucide-react';


const iconMap = {
  'x': X,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-up': ChevronUp,
  'check': Check,
  'circle': Circle,
  'alert-triangle': AlertTriangle,
  'triangle-alert': TriangleAlert,
  'info': Info,
  'book-open': BookOpen,
  'book-open-check': BookOpenCheck,
  'edit-3': Edit3,
  'scale': Scale,
  'bar-chart-horizontal-big': BarChartHorizontalBig,
  'bar-chart-3': BarChart3,
  'award': Award,
  'flask-conical': FlaskConical,
  'brain-circuit': BrainCircuit,
  'brain': BrainCircuit, // Alias
  'folder-open': FolderOpen,
  'tag': Tag,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-down-right': ArrowDownRight,
  'arrow-up-right': ArrowUpRight,
  'trash-2': Trash2,
  'trash': Trash,
  'package-search': PackageSearch,
  'copy': Copy,
  'plus': Plus,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'x-circle': XCircle,
  'loader-2': Loader2,
  'sparkles': Sparkles,
  'save': Save,
  'git-pull-request': GitPullRequest,
  'github': Github,
  'more-vertical': MoreVertical,
  'more-horizontal': MoreHorizontal,
  'history': History,
  'external-link': ExternalLink,
  'help-circle': HelpCircle,
  'pencil': Pencil,
  'file-code-2': FileCode2,
  'file': File,
  'file-text': FileText,
  'git-pull-request-closed': GitPullRequestClosed,
  'refresh-cw': RefreshCw,
  'git-merge': GitMerge,
  'trophy': Trophy,
  'alert-circle': AlertCircle,
  'git-commit': GitCommit,
  'quote': Quote,
  'message-square': MessageSquare,
  'message-circle': MessageCircle,
  'layers': Layers,
  'hash': Hash,
  'layout-grid': LayoutGrid,
  'hard-drive-download': HardDriveDownload,
  'wand-2': Wand2,
  'log-in': LogIn,
  'log-out': LogOut,
  'play-circle': PlayCircle,
  'search': Search,
  'search-x': SearchX,
  'bot': Bot,
  'user': User,
  'users': Users,
  'thermometer': Thermometer,
  'unlink': Unlink,
  'sliders-horizontal': SlidersHorizontal,
  'bar-chart-big': BarChartBig,
  'chevrons-up-down': ChevronsUpDown,
  'terminal': Terminal,
  'thumbs-down': ThumbsDown,
  'server': Server,
  'download': Download,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'star': Star,
  'eye': Eye,
  'wand': Wand,
  'activity': Activity,
  'target': Target,
  'medal': Medal,
  'git-compare-arrows': GitCompareArrows,
  'puzzle': Puzzle,
  'shield': Shield,
  'compass': Compass,
  'globe': Globe,
  'align-left': AlignLeft,
  'git-branch': GitBranch,
  'minimize-2': Minimize2,
  'maximize-2': Maximize2,
  'cpu': Cpu,
  'undo': Undo,
  'keyboard': Keyboard
};

export type IconName = keyof typeof iconMap;

interface IconProps extends LucideProps {
  name: IconName;
  title?: string;
}

const Icon = ({ name, ...props }: IconProps) => {
  const LucideIcon = iconMap[name];
  if (!LucideIcon) {
    return null; // Or return a default icon
  }
  return <LucideIcon {...props} />;
};

export default Icon; 